import { GlobalAlertDialog } from "@/hooks/alert-dialog/component";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import "./globals.css";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-urbanist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={urbanist.variable}>
      <body className={`${urbanist.variable} ${urbanist.variable} antialiased`}>
        <NextTopLoader />
        <GlobalAlertDialog />

        <Toaster />
        {children}
      </body>
    </html>
  );
}
