"use server";

import prisma from "@/lib/db";
import { OrderFormValues } from "../schema";

export async function createOrder(orderData: OrderFormValues) {
  try {
    const order = await prisma.order.create({
      data: {
        customerEmail: orderData.customerEmail,
        customerName: orderData.customerName,
        status: orderData.status,
        customerAddressLine1: orderData.customerAddressLine1,
        customerAddressLine2: orderData.customerAddressLine2,
        customerCity: orderData.customerCity,
        customerState: orderData.customerState,
        customerPostalCode: orderData.customerPostalCode,
        customerCountry: orderData.customerCountry,
        customerPhone: orderData.customerPhone,
        deliveryInstructions: orderData.deliveryInstructions,
        landmark: orderData.landmark,
        orderType: orderData.orderType,
        preferredDeliveryTime: orderData.preferredDeliveryTime,
        amountTotal: orderData.items.reduce(
          (total, item) => total + item.unitPrice * item.quantity,
          0
        ),
        amountSubtotal: orderData.items.reduce(
          (total, item) => total + item.unitPrice * item.quantity,
          0
        ),
        currency: "usd",
        remarks: "Generated by admin",
        items: {
          create: orderData.items.map((item) => ({
            productId: item.productId,
            quantity: item.quantity,
            unitPrice: item.unitPrice,
          })),
        },
      },
      include: {
        items: true,
      },
    });

    return {
      success: true,
      order,
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message,
    };
  }
}
